#! /bin/sh
javac Airport.java
javac Plane.java
javac -cp .:junit-4.12.jar:hamcrest-core-1.3.jar AirportTest.java
java -cp .:junit-4.12.jar:hamcrest-core-1.3.jar org.junit.runner.JUnitCore AirportTest
